version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracledb
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
